CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0} python notebook/infer.py \
    --image_path ${IMAGE_PATH:-notebook/examples/input.jpg} \
    --mask_index ${MASK_INDEX:-1} \
    --output_dir ${OUTPUT_DIR:-outputs} \
    --ss_cache_stride 3 \
    --ss_warmup 2 \
    --ss_order 1 \
    --ss_momentum_beta 0.5 \
    --slat_thresh 1.5 \
    --slat_warmup 3 \
    --slat_carving_ratio 0.1 \
    --mesh_spectral_threshold_low 0.5 \
    --mesh_spectral_threshold_high 0.7 \
    --enable_acceleration
